                                                                                                            # Generated by Django 6.0.7 on 2026-07-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('otasining_ismi', models.CharField(blank=True, max_length=100, null=True)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10)),
                ('telefon_raqam_1', models.CharField(max_length=13, unique=True)),
                ('telefon_raqam_2', models.CharField(blank=True, max_length=13, null=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('telefon_raqam', models.CharField(max_length=13, unique=True)),
                ('parol', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('sotuvchi', 'Sotuvchi'), ('kassir', 'Kassir')], default='kassir', max_length=20)),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
