# Generated by Django 6.0.7 on 2026-07-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodim', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='telefon_raqam_2',
            field=models.CharField(default='', max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
