# Generated by Django 6.0.7 on 2026-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_xodim_user_alter_mijoz_telefon_raqam_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrator'), ('omborchi', 'Omborchi'), ('sotuvchi', 'Sotuvchi')], default='sotuvchi', max_length=20),
        ),
    ]
