# Generated by Django 6.0.7 on 2026-07-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_xodimroli'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimroli',
            name='huquqlar',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
