# Generated by Django 6.0.7 on 2026-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_xodimroli_huquqlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='guruhlar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mijoz',
            name='manzil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mijoz',
            name='teglar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='familiya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='telefon_raqam_2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
