# Generated by Django 6.0.7 on 2026-07-21 14:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('user', '0008_mijoz_guruhlar_mijoz_manzil_mijoz_teglar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MijozQarzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('umumiy_summa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tolangan_summa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('qoldiq_summa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('holat', models.CharField(choices=[('tolanmagan', "To'lanmagan"), ('qisman_tolangan', "Qisman to'langan"), ('tolangan', "To'langan"), ('muddati_otgan', "Muddati o'tgan")], default='tolanmagan', max_length=20)),
                ('muddati', models.DateField(blank=True, null=True)),
                ('eslatma', models.TextField(blank=True, null=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mijoz_qarzlari', to='user.biznes')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qarzlar', to='user.mijoz')),
                ('sotuv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qarz_yozuvlari', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MijozTolovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('summa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tolov_usuli', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('aralash', 'Aralash')], default='naqd', max_length=20)),
                ('eslatma', models.TextField(blank=True, null=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mijoz_tolovlari', to='user.biznes')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='user.mijoz')),
                ('qarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolovlar', to='user.mijozqarzi')),
                ('xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.xodim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SodiqlikDarajasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=100)),
                ('xaridlar_summasi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('chegirma', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sodiqlik_darajalari', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SodiqlikDasturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('turi', models.CharField(choices=[('chegirma', 'Chegirma tizimi'), ('kashbek', 'Keshbek tizimi'), ('ball', 'Ballar tizimi')], default='chegirma', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sodiqlik_dasturi', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
