# Generated by Django 6.0.7 on 2026-07-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_mijozqarzi_mijoztolovi_sodiqlikdarajasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biznes',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biznes',
            name='mamlakat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biznes',
            name='manzil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biznes',
            name='mfo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biznes',
            name='pochta_indeksi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biznes',
            name='soha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biznes',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biznes',
            name='yuridik_manzil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biznes',
            name='yuridik_nomi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='mavzu',
            field=models.CharField(blank=True, default="Yorug'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='pin_kod',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='til',
            field=models.CharField(blank=True, default="O'zbekcha", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='vaqt_mintaqasi',
            field=models.CharField(blank=True, default='Toshkent (GMT +5)', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChekSozlamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(default='Standart', max_length=100)),
                ('chop_etish_turi', models.CharField(default='Chek', max_length=50)),
                ('logotip', models.BooleanField(default=False)),
                ('malumot_bloki', models.BooleanField(default=False)),
                ('mijoz_balansi', models.BooleanField(default=False)),
                ('mijoz_qarzi', models.BooleanField(default=False)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chek_sozlamalari', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
