# Generated by Django 6.0.7 on 2026-07-21 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_biznes_inn_biznes_mamlakat_biznes_manzil_biznes_mfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheksozlamalari',
            name='dokon_nomi_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cheksozlamalari',
            name='logo_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cheksozlamalari',
            name='logo_size',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='cheksozlamalari',
            name='malumot_bloki_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cheksozlamalari',
            name='mijoz_balansi_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cheksozlamalari',
            name='mijoz_qarzi_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='BildirishnomaSozlamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('matrix', models.JSONField(blank=True, default=dict)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnoma_sozlamalari', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MahsulotSozlamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('auto_generate_barcode', models.BooleanField(default=True)),
                ('require_image', models.BooleanField(default=False)),
                ('min_stock_alert', models.PositiveIntegerField(default=10)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot_sozlamalari', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TolovTuriSozlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_asosiy', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tolov_turi_sozlamalari', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Valyuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('kod', models.CharField(max_length=10)),
                ('nomi', models.CharField(max_length=100)),
                ('is_asosiy', models.BooleanField(default=False)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valyutalar', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
