# Generated by Django 6.0.7 on 2026-07-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_cheksozlamalari_dokon_nomi_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('kod', models.CharField(max_length=50)),
                ('nomi', models.CharField(max_length=100)),
                ('is_connected', models.BooleanField(default=False)),
                ('status_text', models.CharField(blank=True, max_length=100, null=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilovalar', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
