# Generated by Django 6.0.7 on 2026-08-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_guruh_teg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mijoz',
            name='guruhlar',
        ),
        migrations.RemoveField(
            model_name='mijoz',
            name='teglar',
        ),
    ]
