# Generated by Django 6.0.7 on 2026-08-03 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_mijoz_guruhlar_remove_mijoz_teglar'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mijoztolovi',
            name='tolov_usuli',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('click', 'Click'), ('aralash', 'Aralash')], default='naqd', max_length=20),
        ),
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('state', models.CharField(choices=[('AWAITING_PHONE', 'Telefon kutilmoqda'), ('AWAITING_PASSWORD', 'Parol kutilmoqda'), ('AUTHENTICATED', "Avtorizatsiyadan o'tgan")], default='AWAITING_PHONE', max_length=50)),
                ('temp_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_sessions', to='user.xodim')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
