# Generated by Django 6.0.7 on 2026-08-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_xodim_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mijoz',
            name='telefon_raqam_1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
