# Generated by Django 6.0.7 on 2026-08-04 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_mijoz_telefon_raqam_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mijoz',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telegramsession',
            name='mijoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_sessions', to='user.mijoz'),
        ),
        migrations.AlterField(
            model_name='telegramsession',
            name='state',
            field=models.CharField(choices=[('AWAITING_PHONE', 'Telefon kutilmoqda'), ('AWAITING_PASSWORD', 'Parol kutilmoqda'), ('AUTHENTICATED', "Avtorizatsiyadan o'tgan"), ('AUTHENTICATED_MIJOZ', "Mijoz avtorizatsiyadan o'tgan")], default='AWAITING_PHONE', max_length=50),
        ),
    ]
