# Generated by Django 6.0.7 on 2026-08-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_mijoz_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsession',
            name='state',
            field=models.CharField(choices=[('AWAITING_PHONE', 'Telefon kutilmoqda'), ('AWAITING_PASSWORD', 'Parol kutilmoqda'), ('AUTHENTICATED', "Avtorizatsiyadan o'tgan"), ('AUTHENTICATED_MIJOZ', "Mijoz avtorizatsiyadan o'tgan"), ('AWAITING_BROADCAST_TYPE', 'Xabar turi kutilmoqda'), ('AWAITING_DEBTOR_SELECTION', 'Mijoz tanlovi kutilmoqda'), ('AWAITING_CONFIRM_ALL_DEBTORS', 'Tasdiqlash kutilmoqda (Barcha)'), ('AWAITING_AD_TEXT', 'Reklama matni kutilmoqda'), ('AWAITING_AD_RECIPIENT_TYPE', 'Reklama qabul qiluvchi turi kutilmoqda')], default='AWAITING_PHONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='telegramsession',
            name='temp_phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
