# Generated by Django 6.0.7 on 2026-07-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('user', '0005_mijoz_biznes_alter_mijoz_telefon_raqam_1_alter_mijoz_telefon_raqam_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='qabul_qilgan_xodim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qabul_qilgan_xarid_buyurtmalari', to='user.xodim'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='yaratgan_xodim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_xarid_buyurtmalari', to='user.xodim'),
        ),
    ]
