# Generated by Django 6.0.7 on 2026-07-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_supplierorder_qabul_qilgan_xodim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yetkazibberuvchi',
            name='biznes',
        ),
    ]
