# Generated by Django 6.0.7 on 2026-07-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_yetkazibberuvchi_biznes'),
        ('products', '0014_yetkazibberuvchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderreturn',
            name='yetkazib_beruvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xarid_qaytarishlari', to='products.yetkazibberuvchi'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='yetkazib_beruvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xarid_buyurtmalari', to='products.yetkazibberuvchi'),
        ),
        migrations.DeleteModel(
            name='YetkazibBeruvchi',
        ),
    ]
