# Generated by Django 6.0.7 on 2026-07-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_supplierorderreturn_yetkazib_beruvchi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorder',
            name='yetkazib_beruvchi',
        ),
        migrations.RemoveField(
            model_name='supplierorderreturn',
            name='yetkazib_beruvchi',
        ),
    ]
