# Generated by Django 6.0.7 on 2026-07-16 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_supplierorder_yetkazib_beruvchi_and_more'),
        ('products', '0015_taminotchi_delete_yetkazibberuvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='taminotchi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='xarid_buyurtmalari', to='products.taminotchi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderreturn',
            name='taminotchi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='xarid_qaytarishlari', to='products.taminotchi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierorderpayment',
            name='tolov_turi',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('uzcard', 'UzCard'), ('humo', 'HUMO'), ('visa', 'VISA'), ('mastercard', 'Mastercard'), ('unionpay', 'UnionPay'), ('ingenico', 'Ingenico')], max_length=30),
        ),
    ]
