# Generated by Django 6.0.7 on 2026-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_supplierorder_taminotchi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderpayment',
            name='tolov_turi',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('uzcard', 'UzCard'), ('humo', 'HUMO'), ('visa', 'VISA'), ('mastercard', 'Mastercard'), ('unionpay', 'UnionPay'), ('ingenico', 'Ingenico'), ('balans_postavshika', 'Yetkazib beruvchi balansi')], max_length=30),
        ),
    ]
