# Generated by Django 6.0.7 on 2026-08-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_supplierorderpayment_tolov_turi'),
        ('user', '0015_xodim_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderpayment',
            name='xodim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_tolovlari', to='user.xodim'),
        ),
    ]
