# Generated by Django 6.0.7 on 2026-07-21 10:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0028_mahsulottoifasi_olchovbirligi'),
        ('user', '0007_xodimroli_huquqlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('kod', models.CharField(max_length=100, unique=True)),
                ('holat', models.CharField(choices=[('yakunlangan', 'Yakunlangan'), ('kechiktirilgan', 'Kechiktirilgan')], default='yakunlangan', max_length=20)),
                ('oraliq_jami', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('chegirma_turi', models.CharField(choices=[('foiz', 'Foiz'), ('summa', 'Summa')], default='foiz', max_length=10)),
                ('chegirma_qiymati', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('chegirma_summasi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('yakuniy_summa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tolangan_summa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('nasiya_summa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tolov_usuli', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('nasiya', 'Nasiya'), ('aralash', 'Aralash')], default='naqd', max_length=20)),
                ('eslatma', models.TextField(blank=True, null=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sotuvlar', to='user.biznes')),
                ('dokon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sotuvlar', to='products.dokon')),
                ('mijoz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sotuvlar', to='user.mijoz')),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sotuvlar', to='user.xodim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('miqdori', models.PositiveIntegerField()),
                ('kelish_narxi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sotish_narxi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_ulgurji', models.BooleanField(default=False)),
                ('jami_summa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sotuv_elementlari', to='products.mahsulot')),
                ('sotuv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementlar', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
