# Generated by Django 6.0.7 on 2026-07-21 14:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_import_chek_raqami_import_column_mapping'),
        ('sales', '0001_initial'),
        ('user', '0009_mijozqarzi_mijoztolovi_sodiqlikdarajasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XarajatKategoriyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=100)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xarajat_kategoriyalari', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('miqdor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tolov_turi', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('nasiya', 'Nasiya'), ('aralash', 'Aralash')], default='naqd', max_length=20)),
                ('sana', models.DateField(blank=True, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xarajatlar', to='user.biznes')),
                ('taminotchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xarajatlar', to='products.taminotchi')),
                ('xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xarajatlar', to='user.xodim')),
                ('kategoriya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xarajatlar', to='sales.xarajatkategoriyasi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
