# Generated by Django 6.0.7 on 2026-07-12 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('shtrix_kod', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('olchov_birligi', models.CharField(choices=[('kg', 'Kilogramm'), ('dona', 'Dona'), ('metr', 'Metr'), ('litr', 'Litr')], max_length=50)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='mahsulotlar/')),
                ('kelish_narxi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ustama', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('sotish_narxi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('miqdori', models.PositiveIntegerField(default=0)),
                ('ogohlantirish', models.PositiveIntegerField(default=0)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
