# Generated by Django 6.0.7 on 2026-07-12 14:33

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_mahsulot_sotish_narxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='mahsulotlar/', validators=[products.models.validate_image_size]),
        ),
    ]
