# Generated by Django 6.0.7 on 2026-07-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_mahsulot_rasm'),
        ('user', '0002_xodim_user_alter_mijoz_telefon_raqam_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('dokon', models.CharField(default='Store Ibrat-uz', max_length=255)),
                ('fayl', models.FileField(upload_to='importlar/')),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('yakunlangan', 'Yakunlangan'), ('xatolik', 'Xatolik')], default='kutilmoqda', max_length=20)),
                ('import_turi', models.CharField(choices=[('kirim', 'Kirim'), ('qoldiq_kirimi', 'Qoldiq kirimi')], default='kirim', max_length=20)),
                ('shtrixkod_generatsiya_qilish', models.BooleanField(default=False)),
                ('miqdori', models.PositiveIntegerField(default=0)),
                ('kelish_summasi', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sotish_summasi', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sotuvlar_taraqqiyoti', models.FloatField(default=0.0)),
                ('elementlar', models.JSONField(blank=True, default=list)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('yakunlagan_xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yakunlagan_importlar', to='user.xodim')),
                ('yaratgan_xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_importlar', to='user.xodim')),
            ],
        ),
    ]
