# Generated by Django 6.0.7 on 2026-07-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_import'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='dokon',
        ),
    ]
