# Generated by Django 6.0.7 on 2026-07-14 12:09

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_import_dokon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='fayl',
            field=models.FileField(upload_to='importlar/', validators=[products.models.validate_import_file_extension, products.models.validate_import_file_size]),
        ),
    ]
