# Generated by Django 6.0.7 on 2026-07-15 09:15

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_import_fayl'),
        ('user', '0003_alter_xodim_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=255, unique=True)),
                ('tavsif', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=255)),
                ('fayl', models.FileField(blank=True, null=True, upload_to='transferlar/', validators=[products.models.validate_import_file_extension, products.models.validate_import_file_size])),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('yakunlangan', 'Yakunlangan'), ('xatolik', 'Xatolik')], default='kutilmoqda', max_length=20)),
                ('miqdori', models.PositiveIntegerField(default=0)),
                ('elementlar', models.JSONField(blank=True, default=list)),
                ('dokondan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuborilgan_transferlar', to='products.dokon')),
                ('dokonga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabul_qilingan_transferlar', to='products.dokon')),
                ('qabul_qilgan_xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qabul_qilgan_transferlar', to='user.xodim')),
                ('yaratgan_xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_transferlar', to='user.xodim')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
