# Generated by Django 6.0.7 on 2026-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_dokon_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='summa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
