# Generated by Django 6.0.7 on 2026-07-16 13:24

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_characteristic_mahsulot_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='rasm',
        ),
        migrations.CreateModel(
            name='MahsulotRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('rasm', models.ImageField(upload_to='mahsulotlar/', validators=[products.models.validate_image_size])),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='products.mahsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
