# Generated by Django 6.0.7 on 2026-07-16 13:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def migrate_barcodes(apps, schema_editor):
    Mahsulot = apps.get_model('products', 'Mahsulot')
    MahsulotShtrixKod = apps.get_model('products', 'MahsulotShtrixKod')
    for prod in Mahsulot.objects.all():
        # Get raw value of shtrix_kod field directly from db using getattr or field lookup
        raw_code = getattr(prod, 'shtrix_kod', None)
        if raw_code:
            if not MahsulotShtrixKod.objects.filter(kod=raw_code).exists():
                MahsulotShtrixKod.objects.create(mahsulot=prod, kod=raw_code)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_mahsulot_rasm_mahsulotrasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahsulotShtrixKod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('kod', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', "Shtrix kod faqat raqamlardan iborat bo'lishi shart.")])),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shtrix_kodlar', to='products.mahsulot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_barcodes, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='mahsulot',
            name='shtrix_kod',
        ),
    ]
