# Generated by Django 6.0.7 on 2026-07-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_mahsulot_shtrix_kod_mahsulotshtrixkod'),
        ('user', '0004_biznes_tarif_xodim_biznes_biznes_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokon',
            name='biznes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokonlar', to='user.biznes'),
        ),
        migrations.AddField(
            model_name='import',
            name='biznes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importlar', to='user.biznes'),
        ),
        migrations.AddField(
            model_name='import',
            name='dokon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importlar', to='products.dokon'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='biznes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='user.biznes'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='biznes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferlar', to='user.biznes'),
        ),
        migrations.CreateModel(
            name='DokonQoldiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('miqdori', models.PositiveIntegerField(default=0)),
                ('ogohlantirish', models.PositiveIntegerField(default=0)),
                ('dokon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoldiqlar', to='products.dokon')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoldiqlar', to='products.mahsulot')),
            ],
            options={
                'unique_together': {('mahsulot', 'dokon')},
            },
        ),
    ]
