# Generated by Django 6.0.7 on 2026-07-16 16:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_mahsulot_artikul_mahsulot_ulgurji_narx'),
        ('user', '0005_mijoz_biznes_alter_mijoz_telefon_raqam_1_alter_mijoz_telefon_raqam_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='YetkazibBeruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=255)),
                ('telefon_raqam', models.CharField(blank=True, max_length=50, null=True)),
                ('balans', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('biznes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkazib_beruvchilar', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
