# Generated by Django 6.0.7 on 2026-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_supplierorder_yetkazib_beruvchi_and_more'),
        ('products', '0014_yetkazibberuvchi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taminotchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=255)),
                ('telefon_raqam', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='YetkazibBeruvchi',
        ),
    ]
