# Generated by Django 6.0.7 on 2026-07-17 09:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_taminotchi_delete_yetkazibberuvchi'),
        ('user', '0005_mijoz_biznes_alter_mijoz_telefon_raqam_1_alter_mijoz_telefon_raqam_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='taminotchi',
            name='balans',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='biznes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taminotchilar', to='user.biznes'),
        ),
    ]
