# Generated by Django 6.0.7 on 2026-07-17 09:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_taminotchi_balans_taminotchi_biznes'),
        ('user', '0005_mijoz_biznes_alter_mijoz_telefon_raqam_1_alter_mijoz_telefon_raqam_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=255)),
                ('sababi', models.CharField(choices=[('defekt', 'Yaroqsiz (Defekt)'), ('yoqotish', "Yo'qotish (Kamomad)"), ('katalogdan_ochirish', "Katalogdan o'chirish"), ('saralash_xatosi', "Saralash xatoligini to'g'rilash"), ('inventarizatsiya', 'Inventarizatsiya'), ('boshqa', 'Boshqa')], default='boshqa', max_length=50)),
                ('holat', models.CharField(choices=[('qoralama', 'Qoralama'), ('yakunlangan', 'Yakunlangan'), ('bekor_qilingan', 'Bekor qilingan')], default='qoralama', max_length=20)),
                ('miqdori', models.PositiveIntegerField(default=0)),
                ('kelish_summasi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sotish_summasi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fayl', models.FileField(blank=True, null=True, upload_to='write_offs/')),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hisobdan_chiqarishlar', to='user.biznes')),
                ('dokon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hisobdan_chiqarishlar', to='products.dokon')),
                ('tasdiqlagan_xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasdiqlagan_hisobdan_chiqarishlar', to='user.xodim')),
                ('yaratgan_xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_hisobdan_chiqarishlar', to='user.xodim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WriteOffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('miqdori', models.PositiveIntegerField()),
                ('kelish_narxi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sotish_narxi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hisobdan_chiqarish_elementlari', to='products.mahsulot')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementlar', to='products.writeoff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
