# Generated by Django 6.0.7 on 2026-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_writeoff_writeoffitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoff',
            name='fayldan_hisobdan_chiqarish',
            field=models.BooleanField(default=False),
        ),
    ]
