# Generated by Django 6.0.7 on 2026-07-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_writeoff_fayldan_hisobdan_chiqarish'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='dokonlar',
            field=models.ManyToManyField(related_name='mahsulotlar', through='products.DokonQoldiq', to='products.dokon'),
        ),
    ]
