# Generated by Django 6.0.7 on 2026-07-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_mahsulot_dokonlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='artikul',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='toifa',
            field=models.CharField(blank=True, default='Mavjud emas', max_length=100, null=True),
        ),
    ]
