# Generated by Django 6.0.7 on 2026-07-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_mahsulot_artikul_mahsulot_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='brend',
            field=models.CharField(blank=True, default='Mavjud emas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='erkin_narx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='taminotchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahsulotlar', to='products.taminotchi'),
        ),
    ]
