# Generated by Django 6.0.7 on 2026-07-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_mahsulot_brend_mahsulot_erkin_narx_and_more'),
        ('user', '0005_mijoz_biznes_alter_mijoz_telefon_raqam_1_alter_mijoz_telefon_raqam_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='XususiyatMaydoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=255)),
                ('tur', models.CharField(choices=[('matn', 'Matn'), ('son', 'Son'), ('tanlov', 'Tanlov (Select)')], default='matn', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xususiyat_maydonlari', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
