# Generated by Django 6.0.7 on 2026-07-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_xususiyatmaydoni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xususiyatmaydoni',
            name='tur',
            field=models.CharField(default='matn', max_length=50),
        ),
    ]
