# Generated by Django 6.0.7 on 2026-07-17 18:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_xususiyatmaydoni_tur'),
        ('user', '0005_mijoz_biznes_alter_mijoz_telefon_raqam_1_alter_mijoz_telefon_raqam_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toplam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('holat', models.CharField(choices=[('qoralama', 'Qoralama'), ('yakunlangan', 'Tasdiqlangan')], default='qoralama', max_length=50)),
                ('miqdori', models.PositiveIntegerField(default=0)),
                ('summa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toplamlar', to='user.biznes')),
                ('dokon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplamlar', to='products.dokon')),
                ('yaratgan_xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_toplamlar', to='user.xodim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToplamElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('miqdori', models.PositiveIntegerField(default=0)),
                ('kelish_narxi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sotish_narxi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplam_elementlari', to='products.mahsulot')),
                ('toplam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementlar', to='products.toplam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
