# Generated by Django 6.0.7 on 2026-07-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_toplam_toplamelement'),
        ('user', '0005_mijoz_biznes_alter_mijoz_telefon_raqam_1_alter_mijoz_telefon_raqam_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='YorliqShablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=255)),
                ('eni', models.FloatField(default=40.0)),
                ('uzunlik', models.FloatField(default=20.0)),
                ('shtrixkod_formati', models.CharField(default='CODE128', max_length=50)),
                ('xususiyatlar', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yorliq_shablonlari', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
