# Generated by Django 6.0.7 on 2026-07-18 10:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_yorliqshablon'),
    ]

    operations = [
        migrations.AddField(
            model_name='taminotchi',
            name='bank_hisob_raqami',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='bank_nomi_filiali',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='eslatma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='mamlakat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='pochta_indeksi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='standart_ustama',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='telefonlar',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='yuridik_manzil',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='yuridik_nomi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
