# Generated by Django 6.0.7 on 2026-07-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_taminotchi_bank_hisob_raqami_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taminotchi',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taminotchi',
            name='mfo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
