# Generated by Django 6.0.7 on 2026-07-21 12:41

import django.db.models.deletion
from django.db import migrations, models


def migrate_characteristics_to_fk(apps, schema_editor):
    Characteristic = apps.get_model('products', 'Characteristic')
    from django.db import connection
    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names()
        through_table = "products_mahsulot_characteristics"
        if through_table in table_names:
            cursor.execute(f"SELECT mahsulot_id, characteristic_id FROM {through_table}")
            for mahsulot_id, characteristic_id in cursor.fetchall():
                try:
                    char_obj = Characteristic.objects.get(id=characteristic_id)
                    char_obj.mahsulot_id = mahsulot_id
                    char_obj.save()
                except Characteristic.DoesNotExist:
                    pass


def migrate_olchov_birligi_to_fk(apps, schema_editor):
    OlchovBirligi = apps.get_model('products', 'OlchovBirligi')
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, biznes_id, olchov_birligi_id FROM products_mahsulot")
        rows = cursor.fetchall()
        for pid, biznes_id, old_val in rows:
            if not old_val or str(old_val).isdigit():
                continue
            
            val_clean = str(old_val).strip().lower()
            unit_obj, created = OlchovBirligi.objects.get_or_create(
                biznes_id=biznes_id,
                short_name=val_clean,
                defaults={'nomi': val_clean.capitalize()}
            )
            cursor.execute(
                "UPDATE products_mahsulot SET olchov_birligi_id = %s WHERE id = %s",
                [unit_obj.id, pid]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_mahsulottoifasi_olchovbirligi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='characteristic',
            name='mahsulot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.mahsulot'),
        ),
        migrations.RunPython(migrate_characteristics_to_fk, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mahsulot',
            name='olchov_birligi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mahsulotlar', to='products.olchovbirligi'),
        ),
        migrations.RunPython(migrate_olchov_birligi_to_fk, reverse_code=migrations.RunPython.noop),
    ]
