# Generated by Django 6.0.7 on 2026-07-21 12:56

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_mahsulot_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='fayl',
            field=models.FileField(blank=True, null=True, upload_to='importlar/', validators=[products.models.validate_import_file_extension, products.models.validate_import_file_size]),
        ),
    ]
