# Generated by Django 6.0.7 on 2026-07-21 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_import_fayl'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplam',
            name='mahsulot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toplam_detallari', to='products.mahsulot'),
        ),
    ]
