# Generated by Django 6.0.7 on 2026-07-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_toplam_mahsulot'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='taminotchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importlar', to='products.taminotchi'),
        ),
        migrations.AddField(
            model_name='import',
            name='tolov_turi',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('nasiya', 'Nasiya'), ('karta', 'Karta')], default='naqd', max_length=20),
        ),
        migrations.AlterField(
            model_name='import',
            name='import_turi',
            field=models.CharField(choices=[('kirim', 'Kirim'), ('qoldiq_kirimi', 'Qoldiq kirimi'), ('qaytarish', 'Qaytarish'), ('ko_chirish', "Ko'chirish")], default='kirim', max_length=20),
        ),
    ]
