# Generated by Django 6.0.7 on 2026-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_import_taminotchi_import_tolov_turi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='chek_raqami',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
