# Generated by Django 6.0.7 on 2026-07-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_import_chek_raqami_import_column_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='olchov_birligi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahsulotlar', to='products.olchovbirligi'),
        ),
    ]
