# Generated by Django 6.0.7 on 2026-08-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_mahsulot_olchov_birligi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokon',
            name='nomi',
            field=models.CharField(max_length=255),
        ),
    ]
