# Generated by Django 6.0.7 on 2026-08-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_dokon_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='taminotchi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
