# Generated by Django 6.0.7 on 2026-08-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_taminotchi_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulottoifasi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
