# Generated by Django 6.0.7 on 2026-08-02 15:22

import django.db.models.deletion
from django.db import migrations, models


def migrate_brend_to_fk(apps, schema_editor):
    MahsulotBrend = apps.get_model('products', 'MahsulotBrend')
    from django.db import connection
    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names()
        if "products_mahsulot" in table_names:
            cursor.execute("SELECT id, biznes_id, brend FROM products_mahsulot")
            rows = cursor.fetchall()
            for pid, biznes_id, old_val in rows:
                if not old_val or old_val == 'Mavjud emas':
                    cursor.execute("UPDATE products_mahsulot SET brend = NULL WHERE id = %s", [pid])
                    continue
                if str(old_val).isdigit():
                    continue
                
                val_clean = str(old_val).strip()
                brand_obj, _ = MahsulotBrend.objects.get_or_create(
                    biznes_id=biznes_id,
                    nomi=val_clean
                )
                cursor.execute(
                    "UPDATE products_mahsulot SET brend = %s WHERE id = %s",
                    [str(brand_obj.id), pid]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_mahsulottoifasi_is_active'),
        ('user', '0013_guruh_teg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahsulotBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('biznes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brendlar', to='user.biznes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_brend_to_fk, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mahsulot',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahsulotlar', to='products.mahsulotbrend'),
        ),
    ]
