# Generated by Django 6.0.7 on 2026-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_mahsulotbrend_alter_mahsulot_brend'),
    ]

    operations = [
        migrations.AddField(
            model_name='taminotchi',
            name='fayl',
            field=models.FileField(blank=True, null=True, upload_to='taminotchilar/'),
        ),
    ]
