# Generated by Django 6.0.7 on 2026-08-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_taminotchi_fayl'),
    ]

    operations = [
        migrations.AddField(
            model_name='olchovbirligi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
