# Generated by Django 6.0.7 on 2026-08-03 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_olchovbirligi_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='ustama',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
